name: Copy Joe Theme from aw168 to awbk

# 触发条件：手动触发
on:
  workflow_dispatch:

# 权限设置
permissions:
  contents: write
  actions: read

jobs:
  copy-theme:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出源仓库（aw168/Joe）
      - name: Checkout source repository (aw168/Joe)
        uses: actions/checkout@v3
        with:
          repository: aw168/Joe
          path: source
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # 需要在 awbk 仓库中配置名为 PERSONAL_ACCESS_TOKEN 的 Secret

      # 2. 检出目标仓库（aw168/awbk）
      - name: Checkout target repository (aw168/awbk)
        uses: actions/checkout@v3
        with:
          repository: aw168/awbk
          path: target
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # 同样使用 PERSONAL_ACCESS_TOKEN

      # 3. 复制 Joe 主题文件
      - name: Copy Joe theme files
        run: |
          # 创建目标目录（如果不存在）
          mkdir -p target/usr/themes/Joe
          # 复制源仓库的所有内容到目标仓库的指定目录
          cp -r source/* target/usr/themes/Joe/

      # 4. 提交更改到目标仓库
      - name: Commit and push changes
        working-directory: target
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add usr/themes/Joe
          git commit -m "Add Joe theme files from aw168/Joe"
          git push
