name: Unzip Joe Theme to usr/themes

# 触发条件：手动触发
on:
  workflow_dispatch:
    inputs:
      zip_filename:
        description: '要解压的 ZIP 文件名 (默认为 Joe.zip)'
        required: true
        default: 'Joe.zip'

# 权限设置
permissions:
  contents: write
  actions: read

jobs:
  unzip-theme:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出目标仓库（aw168/awbk）
      - name: Checkout target repository (aw168/awbk)
        uses: actions/checkout@v3
        with:
          repository: aw168/awbk
          path: target
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      # 2. 设置 up Python (用于 unzip 命令)
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      # 3. 安装 unzip 工具
      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      # 4. 解压文件到目标目录
      - name: Unzip Joe theme
        run: cd target && unzip "${{ github.event.inputs.zip_filename }}" -d usr/themes/

      # 5. 删除 ZIP 文件 (可选)
      - name: Remove ZIP file
        run: cd target && rm "${{ github.event.inputs.zip_filename }}"

      # 6. 提交更改到目标仓库
      - name: Commit and push changes
        working-directory: target
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add usr/themes/Joe
          git commit -m "Unzip Joe theme to usr/themes from ${{ github.event.inputs.zip_filename }}"
          git push
